(define (* a b)
    (define (even? value)
        (= (remainder value 2) 0)
    )
    (define (double x) (+ x x))
    (define (halve x) (/ x 2))
    (define (*-iter value counter result)
        (cond ((= counter 0) result)
              ((even? counter) (*-iter (double value) (halve counter) result))
              (else (*-iter value (- counter 1) (+ value result)))
            )
    )

    (*-iter a b 0)
)